### ISSUE TITLE
Full Text Search 1.0.0

### ISSUE THREAD

**Issue by pmaier1** [owncloud/search_elastic#25]
# Full Text Search 1.0.0

When taking care of a task (and marking as done), please add your name to the task!

### Reason
- First public release https://github.com/owncloud/enterprise/issues/2753
- Would be nice to align with 10.0.10 as the Search API for clients will be released (not a hard req!) and would be good for marketing

### REQUIRED FIXES
- [x] https://github.com/owncloud/search_elastic/pull/28
- [x] BUG: report API issue: https://github.com/owncloud/search_elastic/issues/43 (will affect clients at some point) Fixed with https://github.com/owncloud/search_elastic/pull/83
- [x] BUG: issue with renamed files: https://github.com/owncloud/search_elastic/issues/39
- [x] BUG: issue with shared files: https://github.com/owncloud/search_elastic/issues/36 
- [x] QA: Enable Phan and Stan: https://github.com/owncloud/search_elastic/issues/72 and https://github.com/owncloud/search_elastic/pull/103
- [x] UX: Add Security Questions on destructive commands: https://github.com/owncloud/search_elastic/pull/89

### QA
See https://github.com/owncloud/enterprise/issues/2753#issuecomment-408911586
- [x] Create **QA Milestone**
- [x] Move items from `development` to `qa` 
- [x] Create release branch with the format "release-$version"
- [x] Create "Full Text Search 1.0.0 Testplan" @davitol  https://github.com/owncloud/search_elastic/issues/121
- [x] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) @davitol https://github.com/owncloud/search_elastic/issues/121

### Documentation
- [x] https://github.com/owncloud/docs/pull/1545

### Marketing
- [x] Ping RocketChat channel #marketing - lul
- [x] Check/adapt info.xml stuff https://github.com/owncloud/search_elastic/pull/149
- [x] Check/adapt screenshot https://github.com/owncloud/search_elastic/pull/149
- [ ] Blog post or other communication if applicable

### Build & Marketplace release

All actions to be done on the release branch from here:
- [x] Bump version in info.xml
- [x] Update CHANGELOG.md - Change CHANGELOG.md 'Unreleased' to '$version - $currentDate' (ex: 3.1.5 - 2018-08-01)
- [x] Create github tag for 'v$version'
- [x] Build and sign tarball from github tag 'v$version'
- [x] Smoke test tarball (at least install + enable) @davitol 
- [x] Upload to marketplace
- [x] Publish for customers
- [x] Send mail to release-coordination with link to this ticket and to the changelog
- [ ] Rename QA milestone to '$version'
- [ ] Add a new 'Unreleased' section in CHANGELOG.md
- [x] Create PR to merge changes back to the `master` branch

### Specifics

- [x] Change License in PHP Files
- [x] Add license (GPLv2)
- [x] Open up the repo
- [ ] Anything else I forgot? (it's initial release!)

**Comment by micbar** [comment]
Done. Needs Blogpost @hurradieweltgehtunter
